spring:
  jackson:
    default-property-inclusion: always
  boot: # optional if service discovery is working
    admin:
      client:
        url: http://localhost:8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
