server:
  port: 10000 #${random.int(10000,10010)}
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/payments-development.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
