scrape_configs:
  - job_name: 'shop'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:10000
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:9093
