server:
  port: 20000
api:
  payments: http://PAYMENTS-SERVICE/payments
spring:
  cloud:
    function:
      definition: paymentEventsConsumer
    stream:
      bindings:
        paymentEventsConsumer-in-0:
          destination: payment-events
          group: shop
#    stream:
#      bindings:
#        productsListener-in-0:
#          destination: products-events
#          group: shop
#          binder: kafka1
#      binders:
#        kafka1:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: localhost:9092
discount: "{cipher}15d519679afc3cb66f6e5553e72b9fba5ab269cda49b403756e3a1c6a479b3a3"
