spring:
  application:
    name: reactive-payments-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 006-Tracing-and-monitoring
      #fail-fast: on
      #request-connect-timeout: 10
      #request-read-timeout: 10
