POST http://localhost:10003/payments
Accept: application/json
Content-Type: application/json

{
  "value": "200 PLN"
}

###

GET http://localhost:8080/payments/0481ebd5-7ecf-4844-926e-9b86910a5dc9
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8888/master/application-default.yml

###

GET http://localhost:8888/master/application-development.yml

###

GET http://localhost:8888/master/payments-service.yml

###

GET http://localhost:8888/master/payments-service-development.properties

###

GET http://localhost:8888/main/shop-service.properties

###

POST http://localhost:8080/api/shop/payments
Accept: application/json
Content-Type: application/json

{
  "value": "200 PLN"
}

###

POST http://localhost:20000/orders
Accept: application/json
Content-Type: application/json
Authorization: bearer {{ token }}

{
  "entries": [
    {
      "productId": 1,
      "quantity": 4,
      "price": 2000
    }
  ]
}

###

POST http://localhost:8080/api/shop/orders
Accept: application/json
Content-Type: application/json
Authorization: bearer {{ token }}

{
  "entries": [
    {
      "productId": 1,
      "quantity": 4,
      "price": 2000
    }
  ]
}

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=shop-service

###

POST http://localhost:10003/payments
Accept: application/json
Content-Type: application/json

{
  "value": "200 PLN"
}

###

POST http://localhost:8888/encrypt

10

###

POST http://localhost:8888/decrypt

e97426f47336171ce6dd6838cba9613b8415de29fdb92c916c5646ce2d4401ad

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=password&username=client&password=123

> {%
   client.global.set('token', response.body.access_token);
   client.global.set('refreshToken', response.body.refresh_token);
 %}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=training-client&grant_type=refresh_token&refresh_token={{ refreshToken }}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}
